name: 'Run Hugo/Pagefind and deploy to GitHub Pages'
description: 'Runs Hugo and Pagefind and then deploys the result to GitHub Pages.'
# This composite Action requires the following things in the calling workflow:
#
# permissions:
#   pages: write # to deploy to GitHub Pages
#   id-token: write # to verify that the deployment source is legit
# environment:
#   name: github-pages
#   url: ${{ steps.<id-of-deployment-step>.outputs.url }}
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: true
outputs:
  url:
    description: The URL to which the site was deployed
    value: ${{ steps.deploy.outputs.page_url }}
runs:
  using: "composite"
  steps:
    - name: setup GitHub Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: install Hugo ${{ env.HUGO_VERSION }}
      shell: bash
      env:
        HUGO_VERSION: 0.136.2
      run: |
        set -x &&
        curl -Lo '${{ runner.temp }}/hugo.deb' \
          https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_${HUGO_VERSION}_linux-amd64.deb &&
        sudo dpkg -i ${{ runner.temp }}/hugo.deb
    - name: run Hugo to build the pages
      env:
        HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
        HUGO_ENVIRONMENT: production
      shell: bash
      run: hugo --baseURL "${{ steps.pages.outputs.base_url }}/"
    - name: run Pagefind to build the search index
      shell: bash
      run: npx -y pagefind --site public
    - name: upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public
    - name: deploy
      id: deploy
      uses: actions/deploy-pages@v4
